import sqlite3
import csv
import re
con = sqlite3.connect('mutations.db')
cur = con.cursor()
hugo_Symbol_At = 0
chromosome_At = 0


thing = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P07358" ')
thing0 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8TDI0" ')
thing1 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P35268" ')
thing2 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O94827" ')
thing3 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P56645" ')
thing4 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O95155" ')
thing5 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O00187" ')
thing6 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q96T58" ')
thing7 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9HCE6" ')
thing8 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9UKD2" ')
thing9 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5TIE3" ')
thing10 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O43432" ')
thing11 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8IYB3" ')
thing12 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P19634" ')
thing13 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P17040" ')
thing14 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O95886" ')
thing15 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q99062" ')
thing16 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O94854" ')
thing17 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q96AQ2" ')
thing18 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5T4W7" ')
thing19 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q2M3M2" ')
thing20 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P07358" ')
thing21 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q96N67" ')
thing22 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5VTL7" ')
thing23 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "A2RUH7" ')
thing24 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P09603" ')
thing25 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9HCE1" ')
thing26 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q15431" ')
thing27 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9NXN4" ')
thing28 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q6UY14" ')
thing29 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q86YZ3" ')
thing30 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P06753" ')
thing31 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O15085" ')
thing32 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P50993" ')
thing33 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9UK80" ')
thing34 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5VZP5" ')
thing35 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9C0B6" ')
thing36 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5VZ46" ')
thing37 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P23634" ')
thing38 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O75044" ')
thing39 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8WWW0" ')
thing40 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P20023" ')
thing41 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O75051" ')
thing42 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P17655" ')
thing43 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q92736" ')
thing44 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P42330" ')
thing45 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P27482" ')
thing46 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P19823" ')
thing47 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O60494" ')
thing48 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "B0YJ81" ')
thing49 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q5T848" ')
thing50 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8TEW0" ')
thing51 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q14692" ')
thing52 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P07949" ')
thing53 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q4JDL3" ')
thing54 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "O60269" ')
thing55 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "P50391" ')
thing56 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q711Q0" ')
thing57 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "A6NNA5" ')
thing58 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q96QU1" ')
thing59 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8NE31" ')
thing60 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q8IYB8" ')
thing61 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q9P0M6" ')
thing62 = con.execute('SELECT hugo_symbol FROM mutations WHERE SwissProt_entry_Id = "Q92563" ')
# for n in thing:
# 	print(n[0])
# print(thing)